# Generated by Django 5.0 on 2023-12-16 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('ticket', models.IntegerField()),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('number', models.CharField(max_length=20, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('nrc', models.CharField(max_length=100)),
                ('ref_code', models.CharField(max_length=100)),
                ('ticket_code', models.CharField(blank=True, default='', max_length=20)),
                ('ticket_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('is_approved', models.BooleanField(default=False)),
            ],
        ),
    ]
